version: '3.9'

services:
  nginx:
    image: nginx:1.26
    volumes:
      - ./app/:/var/www/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8882:80"
    networks:
      - myProject

  php-fpm:
    build:
      context: docker/php
    volumes:
      - ./app/:/var/www/app
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=DockerProject1
    networks:
      - myProject

networks:
  myProject:
    driver: bridge