version: '3.9'

services:
  nginx:
    image: nginx:1.26
    platform: linux/x86_64
    volumes:
      - ./app/:/var/www/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${HOST_PORT}:80"
    depends_on:
      - php-fpm
    networks:
      - myProject

  php-fpm:
    build:
      context: docker/php
      args:
        UID: ${UID}
        GID: ${GID}
        UNAME: ${UNAME}
    volumes:
      - ./app/:/var/www/app
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=${COMPOSE_PROJECT_NAME}
    depends_on:
      - db
    networks:
      - myProject

  db:
    image: mariadb:10.11
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_ROOT_HOST: "localhost"
      PHP_IDE_CONFIG: serverName=${COMPOSE_PROJECT_NAME}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${PATH_DB}/${COMPOSE_PROJECT_NAME}/mysql:/var/lib/mysql
    networks:
      - myProject
    logging:
      driver: "json-file"
    ports:
      - "${DEV_DB_PORT}:3306"

networks:
  myProject:
    driver: bridge
